# Generated by Django 4.1.2 on 2022-12-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recien_nacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_recien_nacido', models.IntegerField()),
                ('fecha_de_nacimiento', models.DateField()),
                ('hora_de_nacimiento', models.TimeField()),
                ('peso', models.IntegerField()),
                ('talla', models.IntegerField()),
                ('fecha_de_ingreso', models.DateField()),
                ('motivo_ingreso', models.CharField(max_length=50)),
                ('rut_madre', models.CharField(max_length=10)),
                ('primera_obs', models.TextField()),
            ],
        ),
    ]
