# Generated by Django 4.1.2 on 2022-12-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_madre_padre_remove_recien_nacido_talla'),
    ]

    operations = [
        migrations.CreateModel(
            name='seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_seguimiento', models.IntegerField()),
                ('fecha_de_nacimiento', models.DateField()),
                ('unidad', models.CharField(max_length=50)),
                ('cama', models.CharField(max_length=10)),
                ('tiene_orina', models.CharField(max_length=15)),
                ('tiene_deposicion', models.CharField(max_length=15)),
                ('observaciones', models.TextField()),
                ('matrona', models.CharField(max_length=50)),
            ],
        ),
    ]
